### PR TITLE
fix(stat): support throwIfNoEntry for `statSync`

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Comment by songhobby** [comment]
Can someone merge this? This bug breaks lots of things depending on it

**Comment by peteromano** [comment]
@bluelovers Nuxt3 development and the whole internet and world is broken until this is merged.

See: https://github.com/nuxt/framework/issues/2599#issuecomment-1004848828

Priority level 5000.

image

**Comment by songhobby** [comment]
> @bluelovers Nuxt3 development and the whole internet and world is broken until this is merged.
> 
> See: [nuxt/framework#2599 (comment)](https://github.com/nuxt/framework/issues/2599#issuecomment-1004848828)
> 
> Priority level 5000.
> 
> image

I come from Next.js world, same thing. The world is broken until this is MERGED!

**Comment by isaacs** [comment]
Landed and published.  You can all stop posting memes and blowing up my notifications on social media now.

Listen.  I'm sensitive to the frustration that you feel when something breaks because of a change that some part of the system didn't know to accommodate.  Especially when it's not something you can fix easily.

That said, if a piece of code just sitting there not changing can *break the whole internet*, then I don't know, maybe it *should* be broken.  Did you consider that this is a bug in the thing that calls `statSync({ throwIfNoEntry: false })`?  That perhaps _it_ shouldn't be used with graceful-fs?  Or maybe that the thing using graceful-fs shouldn't be using it in the way it does?  Or as your app grows into a rube goldberg machine (as every piece of software eventually does), maybe it just doesn't work when you bump to Node.js version higher than 14.17 or using it with whatever updates to whatever things led to it calling `statSync({throwIfNoEntry: false})` through graceful-fs.

Or you could have just, idk, forked this library and maintained it more regularly.  I don't use it much anymore, and frankly, the safest thing to do is just not touch it.

Take a breath.  Touch some grass.  Be nice to people.  It's going to be OK.  This bug is not the thing breaking the world, I **fucking promise you that**.

**Pull request closed without merging**
