### PR TITLE
Fix fs.Stats binding

### PR DESCRIPTION
**Pull request by etiktin**
This commit fixes issue #35

### CODE REVIEW

**Comment by etiktin** [comment]
Prior to node v0.11.13, fs.Stats was set to a constructor implemented in the C++ binding.
In newer versions fs.Stats is defined in js and a reference to the constructor is passed to the binding (see: https://github.com/joyent/node/commit/e9ce8fc82a6d12e790511b62852e820d8be03186).
When we initialize gfs we eval the fs source code and therefor redefine Stats and pass the new reference to the binding. So fs.Stats is no longer the constructor used by the binding which results in errors like:
`fs.statSync(path) instanceof fs.Stats === false`

It wasn't an issue prior the 3.0.4 relese because before that version gfs was created by cloning the original and replacing/extending just what was needed (monkey patching) instead of using eval.

To fix it, straight after the eval, we reset the binding to use fs.Stats and set gfs.Stats to fs.Stats.

It's also possible to implement it by manipulating the fs source before passing it to the vm (e.g. replace `fs.Stats = ` with `fs.Stats = module.exports.Stats || ` and pass fs.Stats to fn through module.exports), but it's arguably harder to follow/maintain.

@isaacs, what do you think?

**Comment by isaacs** [comment]
Monkey-patching the core fs global is a huge problem.  That's why it was switched.

Evaluating the internal code is also raising a lot of issues.

https://github.com/isaacs/node-graceful-fs/issues/41
https://github.com/nodejs/io.js/issues/1898

The solution isn't obvious, and I'd like to figure out how we defer EMFILE errors effectively (without falling over with streams etc or falling out of sync with node's fs) before diving too deeply into this relatively minor edge case.

**Comment by etiktin** [comment]
This PR just solves an issue that happens with the current evaluation strategy that breaks the behavior of the global fs module. The fix shouldn't introduce new issues, because it uses code that is already called during the eval.

The issues you mentioned and issue #35, are solvable using the eval strategy so I wouldn't be quick to give up on it. If you add a stage where you transform the code prior to the eval, you can replace the problematic code. For this to be sustainable, you (or any other contributor) must follow the changes to fs so you can prepare the transform in time and provide feedback.

**Comment by isaacs** [comment]
Fixed already on latest releases.

**Pull request closed without merging**
