### PR TITLE
amazing-graceful-fs integration

### PR DESCRIPTION
**Pull request by heavyk**
I thought @bnoordhuis implementation was quite elegant.
@isaacs said to make a PR, and since no one jumped on the opportunity, I did it over lunch. very nice.

I also cherry picked an extra test case from @etiktin from #42 

ref: https://github.com/nodejs/io.js/pull/2026

cheers

### CODE REVIEW

**Comment by etiktin** [comment]
@heavyk, I agree, it is quite elegant :)

I don't know what are the long term plans for amazing-graceful-fs, but if the author is going to maintain it as a separate project it's probably better to use it as an internal module instead of copy-pasting it into graceful-fs.

**Comment by isaacs** [comment]
Since @bnoordhuis hasn't published it, I think maybe it's safe to assume that copy-pasta is the way forward.  Need to include Ben's copyright to be compliant with the ISC license, though.  I'll handle that when I merge this, no need to get it in this PR.

**Comment by heavyk** [comment]
sounds good.
glad you're gonna take care of that bit :)

cheers

**Comment by isaacs** [comment]
Turns out this doesn't work on 0.8.

Supporting Node 0.8 is WAY more important than io.js 2.x, so I'll have to revert this until another solution can be found, unfortunately.

Sorry for getting anyone's hopes up.

**Comment by bnoordhuis** [comment]
I don't have time right now but I'll take a look next week.

**Comment by heavyk** [comment]
ah that's a shame.. if I find time,
I'll have a look too. it'll be interesting

side note: if this can't be fixed easily - and since nan doesn't even support 0.8 anymore,
would it be reasonable to just drop 0.8 support for versions above 3.0?

**Comment by isaacs** [comment]
npm won't drop 0.8 support any time soon. A huge percentage of our users rely on it. (As of last month, was around 10x the iojs usage in fact!)

What we can do is monkeypatch or eval on 0.8, since those approaches still work. Or we could re-implement just the streamson that version, since they aren't changing any time soon.

**Comment by heavyk** [comment]
holy shit, I had no idea... that's incredible.. I honestly thought node-0.8.x was virtually dead. I suppose they're run on PCs with non-retina screens too... just. wow

that's a good idea. if I were to take that approach... I take the existing streams implementation and put it in a separate file. only require that if node version is 0.8?

**Comment by heavyk** [comment]
I got it working how you said. I made a separate branch and pushed there. see #46 .. should I just push it here?

**Comment by isaacs** [comment]
> I suppose they're run on PCs with non-retina screens too... just. wow

Developer machines are about 50% run on OS X, ~40% on Windows, and the remainder on Linux.  The overwhelming majority of deploys are on Linux.  Mostly people using 0.8 are working at a job where they started building their stack on that, and haven't upgraded for plenty of good business reasons, or have started using new Node for new stuff, but haven't revisited old stuff.  If it ain't broke, don't fix it!

**Comment by heavyk** [comment]
very reasonable.. good to have that perspective.

side note: can npm make some of these stats public to kind of help the devs better target our audience? this discussion is a good example. I would have just let those 0.8 guys eat shit if I hadn't of known that stat..

**Pull request merged**
